alias: Sleeping
trigger:
  platform: time
  # When 'after' is used, you cannot also match on hour, minute, seconds.
  # Military time format.
  after: '23:00:00'
action:
  service: homeassistant.turn_on
  entity_id: script.sleep
